#!/usr/bin/env bash

echo "Generating python service libraries..."

python -m grpc_tools.protoc -I. --proto_path=. ./test_grpc_service.proto --python_out=. --grpc_python_out=.

echo "Complete generating service libraries."

