# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_grpc_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_grpc_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17test_grpc_service.proto\"*\n\x17TestGrpcApiRouteRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\x18TestGrpcApiRouteResponse\x12\x10\n\x08response\x18\x01 \x01(\t2Z\n\x0fTestGrpcService\x12G\n\x10TestGrpcApiRoute\x12\x18.TestGrpcApiRouteRequest\x1a\x19.TestGrpcApiRouteResponseb\x06proto3'
)




_TESTGRPCAPIROUTEREQUEST = _descriptor.Descriptor(
  name='TestGrpcApiRouteRequest',
  full_name='TestGrpcApiRouteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='TestGrpcApiRouteRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=69,
)


_TESTGRPCAPIROUTERESPONSE = _descriptor.Descriptor(
  name='TestGrpcApiRouteResponse',
  full_name='TestGrpcApiRouteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='TestGrpcApiRouteResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['TestGrpcApiRouteRequest'] = _TESTGRPCAPIROUTEREQUEST
DESCRIPTOR.message_types_by_name['TestGrpcApiRouteResponse'] = _TESTGRPCAPIROUTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestGrpcApiRouteRequest = _reflection.GeneratedProtocolMessageType('TestGrpcApiRouteRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTGRPCAPIROUTEREQUEST,
  '__module__' : 'test_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:TestGrpcApiRouteRequest)
  })
_sym_db.RegisterMessage(TestGrpcApiRouteRequest)

TestGrpcApiRouteResponse = _reflection.GeneratedProtocolMessageType('TestGrpcApiRouteResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTGRPCAPIROUTERESPONSE,
  '__module__' : 'test_grpc_service_pb2'
  # @@protoc_insertion_point(class_scope:TestGrpcApiRouteResponse)
  })
_sym_db.RegisterMessage(TestGrpcApiRouteResponse)



_TESTGRPCSERVICE = _descriptor.ServiceDescriptor(
  name='TestGrpcService',
  full_name='TestGrpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=117,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestGrpcApiRoute',
    full_name='TestGrpcService.TestGrpcApiRoute',
    index=0,
    containing_service=None,
    input_type=_TESTGRPCAPIROUTEREQUEST,
    output_type=_TESTGRPCAPIROUTERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTGRPCSERVICE)

DESCRIPTOR.services_by_name['TestGrpcService'] = _TESTGRPCSERVICE

# @@protoc_insertion_point(module_scope)
