# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/test_grpc_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotos/test_grpc_service.proto\"*\n\x17TestGrpcApiRouteRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\x18TestGrpcApiRouteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Z\n\x0fTestGrpcService\x12G\n\x10TestGrpcApiRoute\x12\x18.TestGrpcApiRouteRequest\x1a\x19.TestGrpcApiRouteResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.test_grpc_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTGRPCAPIROUTEREQUEST._serialized_start=34
  _TESTGRPCAPIROUTEREQUEST._serialized_end=76
  _TESTGRPCAPIROUTERESPONSE._serialized_start=78
  _TESTGRPCAPIROUTERESPONSE._serialized_end=121
  _TESTGRPCSERVICE._serialized_start=123
  _TESTGRPCSERVICE._serialized_end=213
# @@protoc_insertion_point(module_scope)
